/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnoseIdRouteImport } from './routes/diagnose.$id'
import { Route as CampaignIdRouteImport } from './routes/campaign.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseIdRoute = DiagnoseIdRouteImport.update({
  id: '/diagnose/$id',
  path: '/diagnose/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIdRoute = CampaignIdRouteImport.update({
  id: '/campaign/$id',
  path: '/campaign/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/diagnose/$id': typeof DiagnoseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/diagnose/$id': typeof DiagnoseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/diagnose/$id': typeof DiagnoseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/campaign/$id' | '/diagnose/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/campaign/$id' | '/diagnose/$id'
  id: '__root__' | '/' | '/campaign/$id' | '/diagnose/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignIdRoute: typeof CampaignIdRoute
  DiagnoseIdRoute: typeof DiagnoseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose/$id': {
      id: '/diagnose/$id'
      path: '/diagnose/$id'
      fullPath: '/diagnose/$id'
      preLoaderRoute: typeof DiagnoseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$id': {
      id: '/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/campaign/$id'
      preLoaderRoute: typeof CampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignIdRoute: CampaignIdRoute,
  DiagnoseIdRoute: DiagnoseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
