/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObservationScheduleIdRouteImport } from './routes/observation-schedule.$id'
import { Route as DiagnoseIdRouteImport } from './routes/diagnose.$id'
import { Route as CampaignIdRouteImport } from './routes/campaign.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservationScheduleIdRoute = ObservationScheduleIdRouteImport.update({
  id: '/observation-schedule/$id',
  path: '/observation-schedule/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseIdRoute = DiagnoseIdRouteImport.update({
  id: '/diagnose/$id',
  path: '/diagnose/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignIdRoute = CampaignIdRouteImport.update({
  id: '/campaign/$id',
  path: '/campaign/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/diagnose/$id': typeof DiagnoseIdRoute
  '/observation-schedule/$id': typeof ObservationScheduleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/diagnose/$id': typeof DiagnoseIdRoute
  '/observation-schedule/$id': typeof ObservationScheduleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/campaign/$id': typeof CampaignIdRoute
  '/diagnose/$id': typeof DiagnoseIdRoute
  '/observation-schedule/$id': typeof ObservationScheduleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/campaign/$id'
    | '/diagnose/$id'
    | '/observation-schedule/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/campaign/$id'
    | '/diagnose/$id'
    | '/observation-schedule/$id'
  id:
    | '__root__'
    | '/'
    | '/landing'
    | '/login'
    | '/campaign/$id'
    | '/diagnose/$id'
    | '/observation-schedule/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  CampaignIdRoute: typeof CampaignIdRoute
  DiagnoseIdRoute: typeof DiagnoseIdRoute
  ObservationScheduleIdRoute: typeof ObservationScheduleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observation-schedule/$id': {
      id: '/observation-schedule/$id'
      path: '/observation-schedule/$id'
      fullPath: '/observation-schedule/$id'
      preLoaderRoute: typeof ObservationScheduleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose/$id': {
      id: '/diagnose/$id'
      path: '/diagnose/$id'
      fullPath: '/diagnose/$id'
      preLoaderRoute: typeof DiagnoseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$id': {
      id: '/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/campaign/$id'
      preLoaderRoute: typeof CampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  CampaignIdRoute: CampaignIdRoute,
  DiagnoseIdRoute: DiagnoseIdRoute,
  ObservationScheduleIdRoute: ObservationScheduleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
